# Generated by Django 4.0.1 on 2022-01-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('option_1', models.CharField(max_length=30)),
                ('option_2', models.CharField(max_length=30)),
                ('option_3', models.CharField(max_length=30)),
                ('option_1_count', models.IntegerField(default=0)),
                ('option_2_count', models.IntegerField(default=0)),
                ('option_3_count', models.IntegerField(default=0)),
            ],
        ),
    ]
